//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class company_management_Entities : DbContext
    {
        public company_management_Entities()
            : base("name=company_management_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<checkin_checkout> checkin_checkout { get; set; }
        public virtual DbSet<leaveRequest> leaveRequests { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<project> projects { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<task> tasks { get; set; }
        public virtual DbSet<team> teams { get; set; }
        public virtual DbSet<user_salary> user_salary { get; set; }
        public virtual DbSet<user_team> user_team { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual int USP_AddProject(Nullable<int> idCreator, Nullable<int> idAssignee, string name, string description, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, Nullable<int> progress, Nullable<int> idTeam, Nullable<double> bonus)
        {
            var idCreatorParameter = idCreator.HasValue ?
                new ObjectParameter("idCreator", idCreator) :
                new ObjectParameter("idCreator", typeof(int));
    
            var idAssigneeParameter = idAssignee.HasValue ?
                new ObjectParameter("idAssignee", idAssignee) :
                new ObjectParameter("idAssignee", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("startDate", startDate) :
                new ObjectParameter("startDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var progressParameter = progress.HasValue ?
                new ObjectParameter("progress", progress) :
                new ObjectParameter("progress", typeof(int));
    
            var idTeamParameter = idTeam.HasValue ?
                new ObjectParameter("idTeam", idTeam) :
                new ObjectParameter("idTeam", typeof(int));
    
            var bonusParameter = bonus.HasValue ?
                new ObjectParameter("bonus", bonus) :
                new ObjectParameter("bonus", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_AddProject", idCreatorParameter, idAssigneeParameter, nameParameter, descriptionParameter, startDateParameter, endDateParameter, progressParameter, idTeamParameter, bonusParameter);
        }
    }
}
