//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FullScreenAppDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public project()
        {
            this.tasks = new HashSet<task>();
        }
    
        public int id { get; set; }
        public int idCreator { get; set; }
        public Nullable<int> idAssignee { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<int> idTeam { get; set; }
        public Nullable<double> bonus { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        public virtual team team { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<task> tasks { get; set; }
    }
}
